/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testOpen() {
        Percolation classUnderTest = new Percolation(4);
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isOpen(0, 0));
    }
}
